apiVersion: apps/v1
kind: Deployment
metadata:
  name: newjavaapp-deploy
  labels:
    app: myjavaapp
spec:
  replicas: 3
  selector:
      matchLabels:
         app: newjavaapp
  template:
     metadata:
       labels:
         app: myjavaapp
     spec:
       containers:
       - name: newjavaapp-container
         image:  raghava441/newjavaapp:1
         ports:
         - containerPort: 8080