apiVersion: v1
kind: Service
metadata:
   name: newjavaapp-svc
   labels:
     app: newjavaapp
     
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
  selector:
     app: newjavaapp